### **Exercici 1**

Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un Pandas Dataframe.  
Explora les dades que conté, explica breument quines variables hi ha i queda’t únicament amb les columnes que consideris rellevants.  
Justifica la teva elecció.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('DelayedFlights.csv')
pd.set_option('display.max_columns', 35)
df = df.drop(columns = ['Unnamed: 0'],)
df.head(2)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,N712SW,128.0,150.0,116.0,-14.0,8.0,IAD,TPA,810,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,N772SW,128.0,145.0,113.0,2.0,19.0,IAD,TPA,810,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN

### **Exercici 2**  

Fes un informe complet del dataset:  

Resumeix estadísticament el dataset i les columnes d’interès. Fes una anàlisi estadístic del que consideris rellevant.   
Troba quantes dades faltants hi ha per columna.  
Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...).  
Fes una taula de les aerolínies amb més endarreriments acumulats.  
Quins són els vols més llargs? I els més endarrerits? Busca les rutes més llargues i les que acumulen més retards.  
Aporta allò que consideris rellevant.

In [2]:
import random

# Reducción a 200.000 registros
Indices_Nueva = random.sample(range(len(df) + 1), 200000)
data = df.iloc[Indices_Nueva]
data = data.copy()

data.shape

(200000, 29)

In [3]:
data = data.drop(columns = ['Year'])
data = data.drop(columns = ['TailNum'])
data = data.drop(columns = ['FlightNum'])
data = data.drop(columns = ['DepTime', 'CRSDepTime', 'ArrTime', 'CRSArrTime'])

In [4]:
data.head(3)

,Month,DayofMonth,DayOfWeek,UniqueCarrier,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
1751194,12,19,5,WN,109.0,95.0,90.0,51.0,37.0,IND,MCI,451,8.0,11.0,0,N,0,12.0,0.0,14.0,0.0,25.0
1003198,6,21,6,FL,121.0,139.0,105.0,1.0,19.0,ATL,LGA,761,6.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1831292,12,30,2,US,132.0,122.0,103.0,20.0,10.0,FLL,CLT,631,7.0,22.0,0,N,0,10.0,0.0,10.0,0.0,0.0

In [5]:
data = data.sort_index()
data = data.copy()
data.head(3)

,Month,DayofMonth,DayOfWeek,UniqueCarrier,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
6,1,3,4,WN,130.0,135.0,106.0,1.0,6.0,IND,MCO,828,5.0,19.0,0,N,0,NaN,NaN,NaN,NaN,NaN
9,1,3,4,WN,228.0,240.0,213.0,15.0,27.0,IND,PHX,1489,7.0,8.0,0,N,0,3.0,0.0,0.0,0.0,12.0
15,1,3,4,WN,54.0,70.0,47.0,-7.0,9.0,ISP,BWI,220,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN

Les dades fan referència als retards i cancel·lacions de vols als Estats Units al 2008.  
Les columnes reflecteixen les característiques dels vols per poder valorar les incidències (Data del vol, aeroport d'origen i destí, hores d'enlairament i aterratge, horaris previstos, temps de vol, retard a l'aire, companyia aèria..).
- Mitjançant .unique, he descartat les columnes que només tenen un valor (Unnamed o, Year).
- He descartat la columna 'TailNum', sembla raonable que les característiques tècniques de l'avió influeixin poc en un retard, en comparació amb altres variables. Part de la seva informació més rellevant seria la companyia a què pertany i aquesta informació està en una columna per si sola.
- He descartat també el número de vol. Encara que hi ha certes practiques habituals com adjudicar números parells als vols dirigits a l'Est i Nord (i imparells als contraris) o adjudicar tres digitos a la llarga distància, hi ha columnes amb les dades d'origen i destí o amb la distància del vol en milles .. A més no deixen de ser practiques habituals i no una dada fiable.
- Atès que les hores de sortida i arribada (tant reals com previstes) són locals i podrien existir canvis horaris i que ja existeixen les columnes amb la diferència real en minuts (tant reals com previstes), he decidit prescindir-ne també.

In [6]:
Comp = list(data['UniqueCarrier'].unique())
print('Num de companyies: ' + str(len(Comp)))
Aerop = list(data['Origin'].unique())
print('Num de aeroports: ' + str(len(Aerop)))
Causa = list(data['CancellationCode'].unique())
print('Num de causes de retard: ' + str(len(Causa)))

Num de companyies: 20
Num de aeroports: 297
Num de causes de retard: 4

A la taula, apareixen 20 companyies aèries.  
Apareixen 303 aeroports.  
Apareixen 4 causes de retard.

In [7]:
Ret_Comp = data['CarrierDelay'].sum(skipna = True)
Ret_Meteo = data['WeatherDelay'].sum(skipna = True)
Ret_Aerop = data['NASDelay'].sum(skipna = True)
Ret_Seg = data['SecurityDelay'].sum(skipna = True)
# (Este de momento no lo uso porque es el retraso del vuelo anterior acumulado -creo-)
Ret_Ret = data['LateAircraftDelay'].sum(skipna = True)
Ret_Total = Ret_Comp + Ret_Meteo + Ret_Aerop + Ret_Seg

Per saber el retard acumulat per cada causa he fet la suma de tota la columna, sabent així quant acumula cada retard al llarg de l'any.  
Es pot apreciar que pràcticament tot el retard és causa de les companyies o els aeroports.

In [8]:
Ret_Comp_pc = round((Ret_Comp * 100) / Ret_Total, 2)
Ret_Meteo_pc = round((Ret_Meteo * 100) / Ret_Total, 2)
Ret_Aerop_pc = round((Ret_Aerop * 100) / Ret_Total, 2)
Ret_Seg_pc = round((Ret_Seg * 100) / Ret_Total, 2)

print('Retards per causa de la companyia: ' + str(Ret_Comp_pc) + ' %.')
print('Retards per causa del aeroport: ' + str(Ret_Aerop_pc) + ' %.')
print('Retards per causa de la meteorologia: ' + str(Ret_Meteo_pc) + ' %.')
print('Retards per causa de seguretat: ' + str(Ret_Seg_pc) + ' %.')

Retards per causa de la companyia: 50.43 %.
Retards per causa del aeroport: 39.4 %.
Retards per causa de la meteorologia: 9.93 %.
Retards per causa de seguretat: 0.24 %.

In [9]:
Cancel_Month = data.groupby(['Month', 'CancellationCode']).size()
Cancel_Month

Month  CancellationCode
1      N                   18970
2      N                   19610
3      N                   20646
4      N                   15865
5      N                   15982
6      N                   20513
7      N                   18863
8      N                   16920
9      N                   10033
10     A                       5
       B                       3
       C                       2
       N                   10719
11     A                       8
       B                       2
       N                   10772
12     A                      15
       B                      39
       C                       4
       N                   21029
dtype: int64

Pel que fa a les cancel·lacions, en agrupar-les per mesos,  
estan concentrades a final d'any, als mesos d'octubre, novembre i desembre. La resta del any son causas del aeroport.

In [10]:
# Troba quantes dades faltants hi ha per columna.
faltants = data.isna().sum()
print(faltants)

Month                    0
DayofMonth               0
DayOfWeek                0
UniqueCarrier            0
ActualElapsedTime      939
CRSElapsedTime          15
AirTime                939
ArrDelay               939
DepDelay                 0
Origin                   0
Dest                     0
Distance                 0
TaxiIn                 776
TaxiOut                 58
Cancelled                0
CancellationCode         0
Diverted                 0
CarrierDelay         71057
WeatherDelay         71057
NASDelay             71057
SecurityDelay        71057
LateAircraftDelay    71057
dtype: int64

A la visualització de dalt es poden observar les dades faltants per columna.

In [11]:
# Crea columna velocidad media de vuelo.
data['AvSpeed'] = round((data['Distance']) / ((data['AirTime']) / 60),2)

In [12]:
# Crea columna Gap.
data['Gap'] = (data['CRSElapsedTime']) - (data['ActualElapsedTime'])

In [13]:
# Crea columna si existeix o no retard, en funció de la columna Gap.
def retras(row):
    if row['Gap'] <= 0:
        return 'On Time' 
    else :
        return'Delayed'
data['Status'] = data.apply(retras, axis = 1)

In [14]:
# Crea la columna DistCode, mostrant si és curta o llarga distància.
data['Distance'] = pd.to_numeric(data['Distance'], errors='coerce')

def distancia(row):
    if row['Distance'] <= 400:
        return 'Short'
    else:
        return 'Long'
data['DistCode'] = data.apply(distancia, axis = 1)

In [15]:
data.head(3)

,Month,DayofMonth,DayOfWeek,UniqueCarrier,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,AvSpeed,Gap,Status,DistCode
6,1,3,4,WN,130.0,135.0,106.0,1.0,6.0,IND,MCO,828,5.0,19.0,0,N,0,NaN,NaN,NaN,NaN,NaN,468.68,5.0,Delayed,Long
9,1,3,4,WN,228.0,240.0,213.0,15.0,27.0,IND,PHX,1489,7.0,8.0,0,N,0,3.0,0.0,0.0,0.0,12.0,419.44,12.0,Delayed,Long
15,1,3,4,WN,54.0,70.0,47.0,-7.0,9.0,ISP,BWI,220,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN,280.85,16.0,Delayed,Short

He afegit algunes columnes que crec que poden ser interessants,
bé per ajudar a visualitzar el dataframe o bé per poder treballar-hi més endavant:
- La columna *Gap* És la diferència entre el temps real i l'estimat.
- La columna *DistCode* Divideix els vols entre Llarga i Curta diastància, on es veu que el volum de vols de llarga distància és molt petit en comparació amb els de curta, cosa que sembla que connecta amb el filtratge anterior on la majoria de retards es donaven als vols de curta distància.
- La columna *AvSpeed* És la velocitat mitjana de l'avió (A l'aire) i està expressada a Millas/Hora.
- La columna *Status* mostra si el vol s'ha endarrerit o no.

In [16]:
Gap_Positivo = data[data['Gap'] >= 0]
Comp_Delay = Gap_Positivo.groupby(['UniqueCarrier'])
Comp_Delay['Gap'].sum()

UniqueCarrier
9E     31882.0
AA    119816.0
AQ       551.0
AS     24439.0
B6     43030.0
CO     91218.0
DL     68073.0
EV     47456.0
F9     12202.0
FL     35317.0
HA      2071.0
MQ     71387.0
NW     37746.0
OH     30822.0
OO     59655.0
UA    110995.0
US     80027.0
WN    260773.0
XE     65659.0
YV     36746.0
Name: Gap, dtype: float64

In [17]:
# Comprobació dels retards acumulats
Comp_9E = data[(data['UniqueCarrier'] == '9E') & (data['Gap'] >= 0)]
Comp_9E
Comp_9E['Gap'].sum()

31882.0

In [18]:
Sort_Dist = data.sort_values('Distance', ascending=False)
Sort_Dist.loc[:,['Distance', 'Origin', 'Dest']]

         Distance Origin Dest
871764       4962    EWR  HNL
721700       4962    EWR  HNL
365506       4962    EWR  HNL
1249941      4962    HNL  EWR
1251346      4962    EWR  HNL
...           ...    ...  ...
1615006        31    WRG  PSG
548896         31    WRG  PSG
1456273        30    HPN  JFK
1310363        30    HPN  JFK
774654         11    JFK  LGA

[200000 rows x 3 columns]

A dalt es mostra una taula amb les rutes ordenades de major a menor distància, i sota es mostren les
rutes que acumulen més retards.

In [19]:
Sort_Retr = data.sort_values('Gap', ascending=False)
Sort_Retr.loc[:,['Gap', 'Origin', 'Dest']].head(5)

          Gap Origin Dest
1665355  80.0    JFK  LAX
1469257  78.0    JFK  LAX
1709922  76.0    JFK  LAX
712719   75.0    JFK  LGB
1418278  70.0    EWR  PDX